# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

traceBack <- function(q, i, j, Tm, Tx, Ty) {
    .Call('gphmm_traceBack', PACKAGE = 'gphmm', q, i, j, Tm, Tx, Ty)
}

calculategphmm <- function(x, y, tau, pp, qX, qY, dX, dY, eX, eY) {
    .Call('gphmm_calculategphmm', PACKAGE = 'gphmm', x, y, tau, pp, qX, qY, dX, dY, eX, eY)
}

